name: factoryhouse
favicon: null
layout_spectrum: 0.84338
typography_spectrum: 0.3801
title: factory house
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5834551823791116
  lightness: 0.4096243542153388
  saturation: 0.4375
  rhythmicContrast: 0.6264614195097238
purpose: []
